# These are the orgs/people supporting this project.
# Grant: Solana Foundation Nigeria Grants (Superteam Nigeria)
github: [ch1m3z13]
custom: ["https://superteam.fun/earn/grants/solana-foundation-nigeria-grants/"]
